# Experimental Design and Statistical Considerations

## Introduction

### What

Experimental design encompasses features of a clinical trial that relate to its structure and operations.

### Why

Careful planning and documentation of design of a clinical intervention study is critical for maintenance of rigor and the obtaining of results that are likely to be reproducible. These considerations are intimately connected to the trial's appropriateness for formal statistical analysis and production of results. It is thus imperative that all aspects of design receive the highest level of scrutiny during the planning phase.

### How

It is critical that aspects of design be tailored to the goals and specific aims of the trial. Below we delineate aspects of experimental and statistical design that should be considered. These are not to be considered comprehensive or as being equally applicable to all scenarios, but should provide a starting point in planning your study. 

## Design of the study

### What 

In this toolkit we consider explicitly randomized experiments conducted with human subjects, most typically clinical trials. 

### Why 

Key design features will ultimately dictate the internal validity and generalizability of trial results. 

### How 

The following items should be considered during the design phase.

1. __Rationale for conduct of the trial.__ The scientific / biomedical impetus necessitating conduct of the trial. 
2. __Overall goal.__ What, specifically, the study is intended to accomplish. Investigators should note the degree to which the trial will be considered **explanatory** (that is, focused on estimation of pure causal effects of intervention under controlled circumstances) versus **pragmatic** (focused on choosing between therapeutic options, often under circumstances mimicing or derived directly from clinical experience.) Many studies will have both explanatory and pragmatic aims. 
3. __Illness condition or state.__ The condition modification of which motivates the study.
4. __Sampling population.__ Individuals on whom sampling should focus, including explicit requirements for inclusion and factors that would preclude enrollment (exclusions).
5. __General approach to design.__ Determination of the general nature of the approach to determining intervention efficacy and safety. For instance, the trial may be intended to demonstrate **superiority,** **noninferiority** or **equivalence** of a novel intervention to standard care; to determine **maximum tolerable dose** of a particular agent in a given population; to demonstrate a **dose-response** relation between intervention dosing and endpoints; etc. 
6. __Specific aims.__ Detailed aims addressable by evaluation of statistical hypotheses.
7. __Primary and secondary endpoints.__
8. __General nature of the planned comparisons.__ Key features of the comparisons to be made; e.g. mean performance on a primary endpoint.
9. __Safety concerns.__ Risks, including loss of confidentiality, affiliated with intervention or trial activities. Note that these will be explicitly considered by Institutional Review Board in assessing the risk/benefit ratio of conduct of the trial.
10. __Ethical considerations.__ Additional safety of ethical considerations.
11. __Measurement and quantification of effects.__ The way in which treatment effects will be quantified.
12. __Determination of statistical significance of comparisons.__ Summary nature of quantitative comparisons, fleshed out in statistical analysis plan.
13. __Study staffing and environment.__
    i. __Leadership.__ Designation of membership and roles of investigative team leaders.
    ii. __Staffing.__ Designation of study staff, with specific delineation of responsibilities.
    iii. __Environment.__ Physical space in which the study will be conducted. Explicitly considers access and travel to and from the venue, as appropriate.
14. __Measurement.__ Detailed explication of the was in which measurements will be taken. Makes specific note of resource needs (for instance, whether images or biospecimens must be collected or stored, and the equipment, facilities and human resources necessray to obtain said measures.)
15. __Nature and administration of intervention.__ Specific detail on the intervention, including how, how frequently, and by whom it will be administered and monitored.
16. _Study intervention period._ Length of time over which intervention would be administered, including run-in and washout periods as applicable.
17. __Frequency of participant interactions, data collection and endpoint measurement.__ Number and frequency of participant interactions and measurments; often displayed in tabular format.
18. __Participant allocation or randomization.__ Methods by which participants will be assigned to trial arms, e.g. by randomization. Detail on the specific procedures used to determine these assignments. Must consider factors (e.g. blocking or stratification) that affect this process.
19. __Masking / blinding.__ Determination of whether and how investigators, staff, participants, analysts etc. are aware of intervention assignments. 
20. __Data collection and management.__ Detail on the physical systems for data capture, methods by which it will be captured, the persons performing entry, monitoring of data completeness and quality, etc (see [Data Management](https://ifar-isac.github.io/book/data-management.html) Module).
21. __Statistical design and sample size.__ See below.
22. __Measurement of trial adherence.__ Methods by which completeness of planned participant interactions with randomized activities will be quantified, and plans for analysis, if any.
23. __Training.__ Provisions for training of study personnel, including human resources for providing the trainging.

### Special considerations for older adults

The number of participants available and who would likely consent to be enrolled in trials can be difficult to estimate among older individuals, particularly in the context of numerous exclusionary factors. 

### Common pitfalls

Lack of specificity in describing intervention; insufficient attention to the potential for attrition, data missingness, or intervention non-adherence; lack of detail in considering manner by which participants may be contacted, recruited, and maintained in the trial.

### Resources

## General Statistical Considerations 

### What

The statistical design works hand-in-hand with the experimental design to establish procedures for data interpretation and analysis. Major considerations include planning the enrollment and sample size, the general analytic approach, a priori consideration of the way in which results will be interpreted, and plans to resolve expected and unexpected problems, including data missingness and untoward measurements. 

### Why

Appropriate sample size and a statistical analysis plan are critical for the validity of conclusions and to prevent bias in operations and conclusions. 

### How

Derivation of the statistical analysis plan is detailed in the sections below. 

## Statistical Analysis Plan (SAP)

### What

The project Statistical Analysis Plan (**SAP**) provides detailed descriptions of statistical analyses to be conducted for the trial, including rationale for choice of methods, plans for dealing with unexpected difficulties, and pre-specified guidance on interpretation of results.

### Why

Guidance on data ascertainment, management, storage, analysis and interpretation are critical to preserve the validity of the design and soundness of scientific conclusions.

### How

A version of the SAP may be included as an addendum to or embedded within the study protocol and manual of procedures, but ideally the authoritative SAP should be an independent document with its own formatting, references etc. The SAP must be assembled prior to enrollment and approved by the appropriate parties including the trial statistician, investigative team, and regulatory authorities (e.g. DSMB), and may be included with the package submitted to Institutional Review Boards or equivalent overseeing ethical approval of the trial. Authorship should be by the project statistician, assisted by the investigative team. As with all trials documents, the SAP should be under strict version control, and a 'living' electronic date-stamped version considered the authoritative document (see 
[Essential Documentations](https://ifar-isac.github.io/book/essential-documentations.html) Module). 


#### Contents of the document

The contents of the SAP will vary from trial to trial. For a conventional intervention trial designed to assess efficacy, in which participants are allocated to one of two or more groups (e.g. intervention vs. control), contents might be as follows.

1. __Introduction.__
      a. _Background._ Provides explanatory information concerning disease target, patient population, etc. Includes references to
      authoritative literature.
      b. _Objectives._ Briefly describes overall analytic goals.
          i. Primary objective. Describes primary objective of the trial, being specific concerning such matters as demonstration of
          feasibility; efficacy / effectiveness; safety. Provides some clarity concerning expected treatment effects and public health 
          relevance.
          ii. Secondary objectives. As above, for secondary objectives.
2. __Endpoints.__
      a. _Primary endpoints._ Describes primary and secondary endpoints. May give detail as to measurement, validity and reliability, 
        and other performance characteristics.
      b. _Secondary endpoints._ As above, for secondary endpoints.
3. __Protocol / Grant SAP.__ Summarize existing plan as presented in the original protocol or funding application.  
4. __Design elements.__
      a. _Basic design features._ Discusses overall experimental structure for purposes of comparison.
          i. Nature of primary comparison. Describes the basic target of interest, i.e. determination of superiority, equivalence or 
          noninferiority of intervention to control or current standard of care.
          ii. Participant allocation. Describes randomization or other procedures by which participants are allocated to trial groups.
      b. _Schedule of events._ Gives a summary of time-points and measurements that will be used.
      c. _Blinding._ Describes the degree to which data scientists and personnel are blinded, and maintenance of same.
      d. _Blocking and stratification / matching._ Describes blocking, matching, etc. and references plans for consideration of design 
         effects in analysis.
      e. _Randomization Scheme._ Describes the randomization scheme and procedures.
      f. _Intended Sample Size._ Describes the intended final sample size, referencing potential hurdles such as attrition, crossover, 
         non-adherence and other sources of bias.
      g. _Effects intended to be estimated._ Describes inferential targets for the analysis.
          i. Bounds for determination of statistical significance. Gives clinical and statistical thresholds for determination of 
          significance of evidence and, where appropriate, rejection of null hypotheses.
          ii. Argument for clinical significance. Establishes clinical relevance of effect to be estimated, potentially using the 
          minimum clinically important difference or similar construct.
          iii. _A priori_ determination of interpretation of results.
5. __Analysis Populations / datasets.__ Describes analysis populations.
      a. _Full analysis dataset._ Typically all enrolled participants.
      b. _Intention-to-treat dataset._ Typically all participants allocated to trial groups. Meant to simulate the effect of real-world 
      deployment of intervention.
      c. _Per-protocol dataset._ Typically participants meeting some bound on adherence to trial procedures. Meant to assess causal 
      effect of intervention under adherent conditions.
6. __Detailed Analytic Plan.__ Presents the detailed project analytic plan. Where appropriate this may be organized by specific aim or project objectives.
      a. _Primary endpoint(s)._ Describe primary, supporting and exploratory analyses intended for the Primary Endpoint.
          i. Main analysis of primary endpoint(s). Describes controlling, primary treatment of main analysis.
          ii. Supportive analysis of primary endpoint(s). Describes secondary, supporting version of main analysis.
          iii. Exploratory analysis of primary endpoint(s). Describes additional, perhaps hypothesis-generating analyses, sensitivity 
          assessments, etc.
      b. _Secondary endpoint(s)._ Describe primary, supporting and exploratory analyses intended for the Secondary Endpoints.
          i. Main analysis of secondary endpoint(s). As above, for secondary endpoints.
          ii. Supportive analysis of secondary endpoint(s). As above, for secondary endpoints.
          iii. Exploratory analysis of secondary endpoint(s). As above, for secondary endpoints.
      c. _Safety analysis._ Present plan for analyses of safety signals. Refer to relevant guidance.
          i. Exposure to intervention and trial procedures.
          ii. Adverse events.
          iii. Deaths and Serious Adverse Events.
          iv. Other safety parameters.
      d. _Interim analysis._ Describe the rationale for and operationalization of planned interim analysis. Pay particular attention to 
      the objective – e.g. stopping for futility, demonstrated efficacy, etc.
          i.   Reasons for interim analysis. Briefly provide rationale.
          ii.  Objective of the interim analysis. Describe the objectives of the interim look.
          iii. Planned schedule of interim analysis. Provides the schedule and criteria by which this may be revised.
          iv.  Scope of potential adaptations. Describes ways in which the design may be altered as a result of the interim analysis.
          v.  Stopping rule. Provides the threshold, if any, of evidence that may result in early cessation of the trial for futility 
          and/or for early demonstration of efficacy or other reasons.
          vi. Adjustments to confidence intervals and p-values. Describes the method by which interim analyses will be acknowledged in 
          subsequent data presentations, including management of type-I error rates and related quantities.
          vii. Sample-size re-estimation and conditional power. Describes procedures for re-estimation and summary of conditional power 
          computations.
          viii. Documentation of interim analysis results. Provides template for presentation of results.
7. __Other methodological aspects.__
      a. _Special considerations in measurement._ Here or elsewhere, addresses considerations such as measurement error, technical 
        considerations concerning, for instance, biomarker or imaging analysis, and other specialized considerations.
      b. _Quantification of adherence._ Considers whether adherence to trial procedures should be assessed and analyzed, and if so 
        provides the relevant planning.
      c. _Covariates and subgroups._ Gives descriptions of covariates and subgroups to be considered.
      d. _Handling of missing data._ Describes effect of attrition and other mechanisms dealing with missingness, and analytic plans 
        to take this into account.
      e. _Handling of outliers and unresolved queries._ Describes approaches to dealing with untoward values or unexplained 
        observations. May consider sensitivity analysis or other approaches; should be very specific and explicit.
      f. _Multiplicity adjustments._ Describes plans, if any, to deal with multiple comparisons issues.
      g. _Other considerations._
8. __Reporting conventions.__ Describes manner in which results will be communicated; may include detailed instructions on units, significant digits and rounding, etc.

### Special considerations for older adults

Aging populations are subject to a number of factors that may induce bias or difficulty in analysis, including enhanced risk of attrition or competing risks, elevated prevalence of multimorbidity, difficulties with participant recall, and other factors [cite Van Ness et al]. These and related considerations must be carefully considered within the SAP and during analysis.

### Common pitfalls

Lack of specificity in describing techniques to be used and controlling decisions. Examples: failure to specify method by which standard errors are to be computed (model-based vs. robust. vs. resampling-based methods), failure to specify the set of covariates to be used in the definitive analysis (or method by which that set of covariates will be derived).

### Resources

## Presentation of Pre-planned Statistical Analyses

### What

Presentation of statistical analyses to collaborators within the trial can range from casual exploratory communications to formal presentation of results as described in the SAP. In general, formal inference should follow the pre-specified plan laid out in the SAP, with particular attention to maintenance of blinding and the potential for introduction of bias, and investigators should consult regulations and guidance as to the degree to which discussion of preliminary analyses by the investigative team are appropriate. Formal presentation of results should follow an established template consistent with the SAP and include critical elements as outlined below.

### Why

Protection against confirmation bias and other hazards is critical for the maintenance of rigor and validity of conclusions. Following the agreed-upon template for analyses (as documented in the SAP) provides this protection.

### How

Analyses should be presented in memoranda constructed in a reproducible fashion, with carefully managed version control and documentation of data sources and other items as described below. Authorship should be a collaboration between the study statistician and other members of the analytic team, and must have as a contributor the persons actually performing the analysis.

#### Contents of the document

Some critical items for inclusion are described below

1. __Introduction and objectives.__ Brief background for the proposed analysis, with particular attention to measurement or design issues relevant to the presentation of results.
    a. _Data Sources._ Describes the studies and data set/s used. Must specify the version of the data structures (i.e. the date upon which the dataset was frozen and/or transmitted to the analyst.
    b. _Software and computing environment._ Describes the analytic tools and machinery employed, including version numbers.
    c. _Aims and Analysis Objectives._ Briefly states the aims and hypothesis of the analysis. Includes a brief prose summary how each aim was addressed in the analyses.
2. __Methods.__ Describes analytic sample and methods employed.
    a. _Analytic samples and timeframe._ Defines samples used. Specifies any subgroups to be used in analysis.  Specifies the analysis timeframe (i.e. which visits or measurements were incorporated in analysis).
    b. _Outcome measures._ Specifies the primary and secondary outcomes used in the analysis. If outcomes are derived, provides clear definitions in natural language. Specifies the timepoints at which measures were obtained if not obvious from text above.
    c. _Control Variables._ Lists covariates used in the analyses. Where variables were derived, provide clear definitions. Specifies the timepoints at which measures were obtained, if not obvious from above.
    d. _Statistical Procedures._ Provides the types of statistical methods/models used as well as any statistical tests performed specific to each analytic aim identified above. Identifies primary, supporting and exploratory analyses (see Section XXX).
    e. _Sensitivity Analysis._ Describes and justifies any sensitivity analyses, i.e. using different samples, covariates, methods/models, etc.
    f. _Treatment of missing data._ Describes methods by which missing data are acknowledged and/or taken into account.
    g. _Deviations from SAP or secondary analytic plan._ Describes and justifies any variation in approach from that previously planned.
3. __Presentation of Results.__ Formal presentation of results. Should track closely with [SAP](https://ifar-isac.github.io/book/experimental-design-and-statistical-considerations.html#statistical-analysis-plan) or secondary analytic plan as well as the sections described in Methods (above).
4. __Conclusions.__ Provides in prose the overall implications of the analysis, with high-level quantitative summaries as appropriate.

### Special considerations for older adults

See Special considerations for older adults under the [Statistical Analysis Plan](https://ifar-isac.github.io/book/experimental-design-and-statistical-considerations.html#special-considerations-for-older-adults-1) section.

### Common pitfalls

Failure to acknowledge data sources or describe methods with sufficient detail; failure to conduct and document conclusions in reproducible fashion.

### Resources

## Planning, Conduct and Presentation of Secondary Analyses

Following or in parallel to completion of pre-planned analyses, secondary analyses may be requested or conducted. It is recommended that the trial employ a template for request and design of these analyses that mirrors the structure of the report described in the [Contents of the document](#contents-of-the-document-1) section.

## References
^<sup>1</sup>^Van Ness, P.H., V.R. Towle, and M. Juthani-Mehta (2007) Testing Measurement
Reliability in Older Populations: Methods for Informed Discrimination in Instrument Selection and 
Application. *Journal of Aging and Health* (20) 2: 183-197. DOI: [10.1177/0898264307310448](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.1028.3797&rep=rep1&type=pdf).

Van Ness, P.H., T. E. Murphy, and A. Ali (2016) 
Attention to Individuals: Mixed Methods for N-of-1 Health Care Interventions.  
Journal of Mixed Methods Research DOI: [10.1177/1558689815623685](https://doi.org/10.1177/1558689815623685).
