# Human Subject Protection and Research Regulation

## Introduction
### Module Goal
The goal for this module is to introduce the essential elements of human
subjects’ protections and regulatory requirements pertinent to the
conduct of clinical trials. Essential aspects of human subjects’
protections and regulatory requirements provided in this module include:

-   Institutional Review Boards.
-   Health Insurance Portability and Accountability Act (HIPAA).
-   Data Use Agreements (DUA).
-   ClinicalTrials Registration.
-   Data Safety Monitoring.
-   Informed Consent.
-   Adverse Event Monitoring and Reporting.

### General Considerations About Federal Regulations

The regulation of clinical trials can be complex. What may be seen by
investigators as trivial regulations or minor misdemeanors can have
serious consequences for the individual investigator, their
institutions, sponsors, and trial subjects. Therefore, it is wise to be
over-cautious and anticipate problems before they arise. **As regulatory
issues can play a critical role in your trial design, it is strongly
advised to consider these issues from the very start of project planning
(e.g. grant preparation) by consulting with your Institutional Review
Board (IRB), and making sure you understand existing regulations and
institutional policies.**

Federal agencies including the U.S. Food and Drug Administration (FDA)
and the Department of Health and Human Services (HHS), which includes National
Institutes of Health (NIH), make and enforce regulations to ensure the
safety of participants in clinical trials, and retain final authority
for determining whether an institution has been compliant.
**Investigators should review the specific regulations of the funding or
over-seeing agency and confer with the IRB to determine whether
additional regulations or policies apply. The investigator must keep in
mind that when more than one regulation, guidance, or policy applies the
most stringent must be followed.**

*HHS regulated trials (includes NIH):* HHS requirements for federally
funded human subjects’ research is codified in [45 CFR Part 46
“Protection of Human Subjects”](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/).
This set of regulations are based on the [Belmont
Report](http://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/).

*FDA Regulated Trials:* The FDA has their own set of human subject
regulations and regulations CFR – Code of Federal Regulations Title 21
governing IRB activities, which goes beyond the scope of this module. A
key initial step is to determine whether or not your trial falls under
the regulatory jurisdiction of the FDA which generally oversees drug and
device trials. For more information check [FDA
regulations](http://www.fda.gov/ScienceResearch/SpecialTopics/RunningClinicalTrials/ucm155713.htm).

*Office of Human Research Protections (OHRP):* The OHRP is the federal
body responsible for compliance monitoring. Under Title IV of the Public
Health Service Act (42 USC 281 et seq.), OHRP has the authority to
investigate complaints about human subject protections in HHS-funded
research, or other research covered by the institution’s Assurance of
Compliance. For general regulatory issues, particularly for federally
funded trials, refer to the [OHRP website](http://www.hhs.gov/ohrp/).

*International Conference on Harmonization (ICH) Good Clinical Practice
(GCP):* While federal regulations provide the standards by which human
subjects research is to be conducted, guidance documents and
institutional policies add specificity and provide direction on how to
apply regulatory requirements. One such guidance is the ICH GCP guidance.
Compliance with the [ICH GCP](http://www.ich.org/products/guidelines/efficacy/article/efficacy-guidelines.html) 
assures that the rights and well-being of trial subjects are protected and 
that the clinical trial data are credible.

### Resources
-   Code of Federal Regulations, Title 45 Part 46,<http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/>
-   Belmont Report,
    <http://www.hhs.gov/ohrp/regulations-and-policy/belmont-report/>
-   International Conference on Harmonization (ICH) guidelines for Clinical Good Practice (GCP),
    <http://www.ich.org/products/guidelines/efficacy/article/efficacy-guidelines.html>
-   OHRP, <http://www.hhs.gov/ohrp/>
-   US Food and Drug Administration regulations,
    <http://www.fda.gov/ScienceResearch/SpecialTopics/RunningClinicalTrials/ucm155713.htm>

## Institutional Review Board (IRB)
### What

An Institutional Review Board (IRB) is an appropriately constituted
group formally designated to review, approve and monitor research
involving human subjects to ensure it is conducted in accordance with
applicable federal regulations, institutional policies, and ethical
guidelines.

While all IRBs are responsible to adhere to the same regulations as
defined by [OHRP](http://www.hhs.gov/ohrp/regulations-and-policy),
each IRB is required to have its own institutional policies and operates differently. It is
critical to understand the requirements of the IRB overseeing your
project. Specific information relevant to HSL IRB can be found on the
IRB section of the [HSL
website](http://www.instituteforagingresearch.org/resources/research-administration/institutional-review-board)
as well as the internal HSL [“HUB”](http://thehslhub/Departments/Roslindale/HSL-IFAR/Institutional-Review-Board).

#### Categories of IRB oversight

Depending on the study design and degree to which human subjects are
involved, the IRB will review the research and will make a determination
on the appropriate review level. The basic levels of review include:

-   Exempt (determination by IRB Chair or her designee).
-   Expedited (review/approval by IRB Chair or her designee).

Full Board (review/approval by the convened IRB) Most clinical trials
will require full IRB review.

#### IRB applications and reviews

IRB applications include:

-   Initial application.
-   Annual/continuing review.
-   Amendments/modifications to the protocol or study materials.
-   Incident reports for:
    -   Unanticipated problems.
    -   Non-Compliance.

##### Initial review of research application

All human subjects’ research must be reviewed and approved by an IRB
before human subjects activities can begin. This includes recruitment
efforts, and receiving or collecting data. Per Federal and Institutional
policy, no funds for research involving human subjects activities will
be released until the appropriate IRB approval has been secured.

##### Annual/Continuing review

Investigators must receive continuing approval of their research at
least annually. On some occasions, more frequent review may be required
by the IRB. Continuing approval is required until all activities with
human subjects are complete (this includes access to data with
participant identifiers or with codes that can be linked back to
research participants).

##### Amendment submissions

Investigators must submit all changes to the research or research
materials and receive IRB approval for those changes prior to
implementation (except when necessary to eliminate apparent immediate
hazards to research participants).

### Why

The IRB assures that a clinical trial is in compliance with federal and
state regulations, institutional policies, and accepted ethical
guidelines, to protect the rights and welfare of research subjects.

### How

#### IRB review for single site trials

The procedures for IRB review differ by institution but have common main
elements. It is wise before you embark on your IRB application to
consult with the IRB office to review the general study design and
anticipate key review considerations.

The HSL IFAR IRB uses an electronic submissions system (Cayuse). Forms
are templated and will guide you through the required elements.
Application submissions must meet deadlines stipulated in the [HSL IFAR
IRB Standard Operating Procedures](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx).

#### IRB review for multi-site trials 

Many clinical trials involve multiple sites and/or investigators from
multiple institutions. Many clinical trials involve multiple sites that
are clearly engaged in human subjects’ research (i.e., site personnel
are recruiting subjects, implementing an intervention, or collecting
data). Regulatory oversight of these trials can be done either by:

-   Single IRB review (one IRB reviews the research, and the other IRBs
    rely on the reviewing IRB).
-   Multiple IRB reviews (e.g. each institution conducts its own
    IRB review/approval).

In June 2016, the NIH established a
[policy](http://grants.nih.gov/grants/guide/notice-files/NOT-OD-16-094.html)
effective May 25, 2017, requiring a single IRB for all NIH-funded
multisite studies, with only rare exceptions.

IRBs of engaged sites and investigators may cede oversight
responsibility to the IRB reviewing the research (also referred to as
the IRB of record). Relying on an external IRB, or ceded review, is
documented with a formal agreement between the reviewing and relying
site IRBs and must be signed by an Institutional Official. Note: If you
are conducting research with Harvard affiliates, you may rely on the
Harvard Catalyst Reliance Agreement, rather than an IRB Authorization
Agreement. See the HSL IRB office for more information.

Some study sites engaging in human subjects’ research (e.g., community
nursing homes) may not be associated with an IRB. In this case the
reviewing IRB may agree to provide IRB oversight for the external site
through a formalized agreement (Individual Investigator Agreement)
between the two parties. Alternatively, a commercial IRB may be engaged
in a contract to provide oversight for that external site. Sites that
receive direct federal awards for research purposes may also need a
[FederalWide Assurances](http://www.hhs.gov/ohrp/register-irbs-and-obtain-fwas/fwas/fwa-protection-of-human-subjecct/index.html).
These determinations will be made by the prime IRB responsible for the trial.

### Special Considerations for Older Subjects

There are two special considerations for special protections governing
research with elderly subjects: cognitive impairment and
institutionalization. Under those conditions, a number of issues must be
taken into consideration. See [OHRPs related guidance](http://archive.hhs.gov/ohrp/irb/irb_chapter6.htm) and [HSL IRB’s
Standard Operating Procedures (SOPs)](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx). See
also Informed Consent [(Section 3.7)](## Informed Consent) related to the decision making capacity).

### Common Pitfalls

-   Not seeking IRB guidance in the process of trial design and well in
    advance of your planned start date.
-   Underestimating the time it takes to get IRB approval.
-   Underestimating regulatory requirements. Failure to meet
    requirements could lead to serious consequences for yourself and
    your institution. Be overly cautious and always report anything of
    potential concern to your IRB.
-   Flippant or casual comments about human subjects’ or regulatory
    issues about your trial via emails or text. If a problem occurs, all
    related communication may be become eventually become relevant.

### Resources 
External

-   HHS OHRP Regulations and Policy, <http://www.hhs.gov/ohrp/regulations-and-policy/guidance/index.html>
-   NIH Policy on the Use of a Single IRB for Multi-site Research, <http://grants.nih.gov/grants/guide/notice-files/NOT-OD-16-094.html>
-   U.S. Food and Drug Administration (FDA), <http://www.fda.gov/ScienceResearch/SpecialTopics/RunningClinicalTrials/>

Internal

-   HSL IRB, <http://www.instituteforagingresearch.org/resources/research-administration/institutional-review-board>
-   HSL “HUB”, <http://thehslhub/Departments/Roslindale/HSL-IFAR/Institutional-Review-Board>
-   HSL IFAR IRB Standard Operating Procedures, (<http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx>)

## The Health Insurance Portability and Accountability Act (HIPAA)
### What 
The HIPAA, enacted through the Privacy Rule, establishes national
standards for the protection of protected health information (PHI). The
rule establishes conditions under which PHI may be used by covered
entities^1^, including for research^2^ purposes. With regards to
research, the Privacy Rule also defines the means by which individuals
should be informed of uses of their medical information for research
purposes, and their rights to access information about them held by
covered entities.

^1^***Covered entities**: health plans, health care clearinghouses and
health care providers who transmit any health information in connection
with transactions for which HHS has adopted standards.*

^2^***Research**: Defined in the Privacy Rule “a systematic
investigation, including research development, testing, and evaluation,
designed to develop or contribute to generalizable knowledge.” *

### Why

The Privacy Rule protects the privacy of individually identifiable
health information, while at the same time ensuring that researchers
have access to medical information necessary to conduct vital research.

### How

The [Privacy Rule](http://www.hhs.gov/hipaa/for-professionals/privacy/) builds upon the
protections provided to human subjects in the [Common Rule (45 CFR Part
46, Subpart A)](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/common-rule/), and/or the Food and Drug Administration’s 
(FDA) human subject protection regulations [(21 CFR Parts 50 and 56)](http://osp.od.nih.gov/office-clinical-research-and-bioethics-policy/clinical-research-policy/research-involving-human-subjects). There are three main areas for researchers to consider.

#### Screening patients for recruitment 

Selection of subjects for a clinical trial often requires identifying
patients with specific characteristics (e.g., a diagnosis) from a large
patient population using data considered PHI. To facilitate such
efforts, covered entities are permitted to use and disclose PHI for
research purposes pursuant to a waiver of authorization by an IRB or
Privacy Board. At HSL, the IRB also serves as the Privacy Board.

#### Inclusion of HIPAA assurances in informed consent forms

When PHI is being used in a research study, the consent form must
include core elements and essential language for authorization of use of
PHI as defined by the Privacy Rule (see Privacy Rule, 45
C.F.R. §164.508(c)(1)). At HSL, the required language is included in the
Informed Consent Template available in the online IRB application system
Cayuse. **Investigators should not alter these templates without
consulting the IRB.**

#### Handling of PHI throughout the trial

A core tenant of HIPAA and the use of PHI is to use the minimum
necessary information in order to maintain and protect patient privacy.
As such, clinical trials must be designed and conducted to minimize
unnecessary data collection and maximize subject confidentiality.
Whenever possible, information obtained from patients or their medical
records should be collected without identifiers. When identifiable data
is collected, the protocol must be designed to maintain confidentiality
of identifiable data, and data security measures appropriate to the
degree of risk from disclosure.

A complete summary of key elements of the Privacy Rule including who is
covered, what information is protected, and how PHI can be used and
disclosed is presented in the “[Summary of the HIPAA Privacy
Rule](http://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html).
HSL-specific policies regarding HIPAA, and the use of PHI in research
can be found in the [HSL IRB
SOP](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx). 

### Special considerations for older subjects
NONE

### Common Pitfalls
-   Inadequate protection PHI (e.g., transporting patient files with
    identifiers in an unsecure manner, unencrypted laptops or databases
    that contain PHI etc).

### Resources 

-   Regulatory/Policy, Food and Drug Administration’s (FDA) human subject protection regulations (21 CFR Parts 50 and 56),<http://osp.od.nih.gov/office-clinical-research-and-bioethics-policy/clinical-research-policy/research-involving-human-subjects>
-   HHS Code of Federal Regulations HIPAA for Professionals, <http://www.hhs.gov/hipaa/for-professionals/special-topics/research/index.html>
-   HHS Summary of the HIPAA Privacy Rule, <http://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html>
-   HHS Protecting Person Health Information in Research: Understanding HIPAA Privacy Rule, <https://privacyruleandresearch.nih.gov/pdf/HIPAA_Privacy_Rule_Booklet.pdf>
-   HHS NIH, HIPAA Authorization for Research, <https://privacyruleandresearch.nih.gov/authorization.asp>.
-   Common Rule (45 CFR Part 46, Subpart A), (http://www.hhs.gov/ohrp/regulations-and-policy/regulations/common-rule/)

Internal

-   HSL IRB SOP, <http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx>

## Data Use Agreements (DUA)
### What 
A data use agreement (DUA) is a contractual agreement required under the
Privacy Rule between a HIPAA covered entity (e.g., HSL) and a third
party who wishes to obtain PHI with limited identifiers, referred to as
a Limited Data Set (LDS). DUAs address issues such as limitations on use
of the data, obligations to safeguard the data, liability for harm
arising from the use of the data, publication, and privacy rights that
are associated with transfers of confidential or protected data. Refer
to HIPAA, [Section 45 CFR part 160 Subparts A and E of Part
164](http://www.hhs.gov/ocio/eplc/EPLC%20Archive%20Documents/55-Data%20Use%20Agreement%20(DUA)/eplc_dua_practices_guide.pdf)
for details. A common example of a study that requires a DUA, is one
that utilizes Medicare data for which a DUA must be set up with the
Centers for Medicare and Medicaid. See resources below for guidance.

### Why
In addition to the requirements set forth in the Privacy Rule, a DUA
clearly establishes the rules and expectations related to provision and
use of data by the involved parties (provider and recipient). DUA must
be entered into *before* there is any use or disclosure of a limited
data set to an outside institution or party.

### How
The content, format, and processes of establishing DUAs differ depending
on the entities involved. Investigators must use approved DUA frameworks
at these entities and their institutions. [HSL IFAR policies related to
DUAs](http://thehslhub/~/media/HSLNet/P_P/IFAR/IFARPPCMS.ashx) can be
found on the HUB.

### Special considerations for older subjects 
NONE

### Common Pitfalls
-   Not realizing a DUA is needed.
-   Being unaware the time required to process a DUA, especially with CMS.
-   Being unaware the cost required to use data from certain entities,
    especially CMS.
-   Narrowly written DUAs which do not account for the possibility of
    future analytic plans.

### Resources 

External

-   Academy Health, Privacy Tools: Guidance on HIPAA Data Use
    Agreements, <http://www.hsrmethods.org/PrivacyInResearch/Privacy%20Tools/Guidance%20on%20HIPAA%20Data%20Use%20Agreements.aspx>
-   CMS.gov DUAs, <https://www.cms.gov/Research-Statistics-Data-and-Systems/Computer-Data-and-Systems/Privacy/DUAs.html>
-   HHS CMS DUA, Agreement for use of Centers for Medicare and Medicaid
    Services (CMS) Data containing individual identifiers,
    <https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/sharedsavingsprogram/Downloads/Data-Use-Agreement.pdf>
-   HHS NIH, How can Covered Entities Use and Disclose Protected Health
    Information for Research and Comply with the Privacy Rule?,
    <https://privacyruleandresearch.nih.gov/pr_08.asp>
-   HHS Practice Guide Data Use Agreement,
    <http://www.hhs.gov/ocio/eplc/EPLC%20Archive%20Documents/55-Data%20Use%20Agreement%20(DUA)/eplc_dua_practices_guide.pdf>
-   Research Data Assistance Center, Tips for completing the Data
    Use Agreement with Addendum, <http://www.resdac.org/resconnect/articles/154>

Internal

-   Hebrew Senior Life, Creation, Use, Disclosure and Receipt of
    Limited Data Sets and Data Use Agreements doc, <http://thehslhub/~/media/HSLNet/P_P/IFAR/IFARPPCMS.ashx>

## Clinical Trial Registration
### What
ClinicalTrials.gov is an on-line public registry of clinical trials
maintained by the U.S. National Institutes of Health (NIH) and National
Library of Medicine. It was launched in 2000 and expanded by the Federal
Drug Administration Amendment Act (FDAAA 801) in 2007 and is endorsed by
the International Committee of Medical Journal Editors (ICMJE).

#### Which trials must be registered?

It is strongly recommended that **ALL** clinical trials are registered on
[ClinicalTrials.gov](https://clinicaltrials.gov/). By law, only trials that meet the FDAAA 801
definition of an "applicable clinical trial" must be registered which
generally include interventional studies (with one or more arms) of
FDA-regulated drugs, biological products, or devices. However, in 2014,
the NIH proposed expanding clinicaltrials.gov registration requirements
to include all NIH-funded clinical trials. Thus, even clinical trials in
which the intervention is a behavior modification or clinical education
program merits registration on ClinicalTrials.org. **It is strongly
recommended that ALL clinical trials are registered on
ClinicalTrials.gov.**

### Why
There are numerous reasons for registering a trial. Refer to [Clinicaltrials.gov]((https://clinicaltrials.gov/ct2/manage-recs/background) for elaboration.

#### Required by Law
Section 801 of the Food and Drug Administration Amendments Act [(FDAAA
801)](http://www.gpo.gov/fdsys/pkg/PLAW-110publ85/pdf/PLAW-110publ85.pdf#page=82)
requires Responsible Parties to register and submit summary results of
clinical trials with ClinicalTrials.gov. The law applies to certain
clinical trials of drugs (including biological products) and medical
devices.

#### Required for Journal Publication
The International Committee of Medical Journal Editors [(ICMJE)](http://www.icmje.org/recommendations/browse/publishing-and-editorial-issues/clinical-trial-registration.html) requires trial registration
as a condition of the publication of research results generated by a
clinical trial. ClinicalTrials.gov is a registry where organizations and
individuals can provide the World Health Organization (WHO) [Trial
Registration Data
Set](http://www.who.int/ictrp/network/trds/en/index.html) required by
ICMJE. Top tier journals will scrutinize the registration of your trial
on ClinicalTrials.gov and make sure that is aligns with the description
provided in your paper. **Most journals have a strict requirement that
your trial be registered no more within 21 days after enrollment of the
first participant and will reject your paper it is this is not the
case.**

### How

Trial registry is done on the ClinicalTrials.gov. Protocol Registration
and Results System (PRS). The PI (and in some circumstances, a lead
person on the study team) should be assigned as the Responsible Party
charged with initiating and maintaining the registration. Once submitted
by the PI, institutional administrators (the HSL IRB Director at IFAR)
are notified of the submission and must verify the information in the
registration (including changes and updates to the study) and approve
and release it before it is sent to administrators at ClinicalTrials.gov
for review and eventual posting.

#### Initial submission

The clinical trial must be registered no later than 21 days after
enrollment of the first participant. Note this rule is strictly enforced
by major journals. If initial registration is not done within this
timeframe, the trial results will be disqualified from consideration for
publication. The application and direction are online at [ClinicalTrials.gov](https://clinicaltrials.gov/ct2/manage-recs/how-apply).

#### Registration Updates

Responsible Parties should update their records within 30 days of a
change to any of the following:

-   [Recruitment
    Status](http://prsinfo.clinicaltrials.gov/definitions.html#FacilityStatus)
    and [Overall Recruitment
    Status](http://prsinfo.clinicaltrials.gov/definitions.html#OverallStatus)
    data elements.
-   Completion Date.
-   Outcomes Definitions.
-   Other changes or updates to the record must be made at least every
    12 months.

#### Submitting Results
The Responsible Party MUST submit summary results no later than 12
months after the Completion Date, defined in as the date of final data
collection for the pre-specified "primary outcome measure" (see [Primary
Completion Date data
element](http://prsinfo.clinicaltrials.gov/definitions.html#PrimaryCompletionDate)
on ClinicalTrials.gov). Scientific information is submitted as [four
separate modules](https://clinicaltrials.gov/ct2/manage-recs/how-report\#Overview): Participant Flow, Baseline Characteristics, Outcome
Measures and Statistical Analyses, and Adverse Events.


### Special considerations for older subjects 
NONE

### Common Pitfalls
-   Failing to register the trial.
-   Failing to register the trial within a 21 days of enrolling the
    first participant.
-   Failing to maintain and update trial registration details.
-   Failing submit results.

### Resources 

-   ClinicalTrials.gov,
    <https://grants.nih.gov/ClinicalTrials_fdaaa/docs/registration_flow_chart.pdf>
-   World Health Organization, 
    <http://www.who.int/about/en/>

## Data Safety Monitoring
### What
Funding agencies require that the safety of trial participants and
integrity of data are ensured through systems of research oversight and
monitoring. The type and level of monitoring required depends on the
risk, nature, size and complexity of the clinical trial. It can be as
simple as basic monitoring by the PI, an independent safety officer or
medical monitor, or an NIH officer, or as complex as a full independent
Data Safety Monitoring Board (DSMB). **The decision about the level of
data safety monitoring required for your study is ordinarily determined
by the sponsor (i.e., NIH), but it may also be required by the IRB.**
The remainder of this module assumes your trial requires full DSMB.

The DSMB is a formally appointed independent group, consisting of at
least three (3) voting members external to the research that typically
include experts in the relevant field of study, statistics, and study
design. The clinical trial PI(s) and lead statistician also typically
participate as internal members on the DSMB.

The DSMB conducts interim monitoring of accumulating data from research
activities to assure the continuing safety of human subjects, relevance
of the study question, appropriateness of the study, and integrity of
the accumulating data.

### Why
The purpose of a DSMB is to ensure the safety of human subjects,
relevance of the study question, appropriateness of the study, and
integrity of the accumulating data. Additionally, the DSMB attempts to
identify threats to credibility or the validity of the study related to
slow rates of accrual, high rates of ineligibility after randomization,
high rates of protocol violations, and unexpectedly high dropout rates.

The primary responsibilities of the DSMB are:

-   Periodic review and evaluation of the accumulated study data for
    participant safety, study conduct and progress, and, when
    appropriate, efficacy.
-   Provision of written documentation confirming review of the protocol
    and agreement with the study design and the data safety monitoring
    plan (DSMP).
-   Make recommendations to study sponsor concerning the continuation,
    modification, unmasking or termination of the trial.
-   Provide a written report to the IRB which summarizes oversight
    activities and recommendations, and any concerns regarding
    subject safety.

### How
There are four basic steps in establishing a trial’s Data Safety Monitoring system:

#### Establish a Data Safety Monitoring Plan (DSMP)

The PI should create a Data Safety Monitoring Plan (DSMP) that is
appropriate for the type and expected risks of the research. The DSMP
must be included with the protocol in the initial submission to the IRB.
[Templates of
DSMPs](https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/data-and-safety-monitorin)
are available on the NIH website*. DSMPs* generally include the
following elements:

-   Data or events to be captured under the monitoring provisions (e.g.,
    unanticipated problems and adverse events).
-   The entity responsible (e.g., investigators, sponsor, a coordinating
    or statistical center, an independent monitor, DSMB) for monitoring
    the data collected and the time frames for reporting.
-   The frequency of assessments of data or events captured by the
    monitoring provisions.
-   Definition of specific triggers or stopping rules that dictate when
    action is required.
-   Procedures for communicating to the IRB(s), the study sponsor, the
    investigator(s), and other appropriate officials the outcome of the
    reviews by the monitoring entity.

#### Establish the DSMB membership 
For NIH-funded studies, the Program Official (PO) holds primary
responsibility for the formation of the DSMB and selecting the external
members unless otherwise specified in the Terms of Award. External DSMB
members should not have direct involvement in the conduct of the study
or any financial, proprietary, professional, or other interests that may
affect their impartiality. Study investigators should have opportunity
to review the proposed members before the candidate’s interest and
availability are confirmed.

Once the group has been formed, the PO will select the DSMB Chair. All
external DSMB must sign a Conflict of Interest certification that should
be kept in the Essential Documents binder. Each IRB should be informed
of the membership and operating procedures.

#### Create DSMB Charter
Before the trial begins a DSMB charter must be prepared that details the
roles and responsibilities of the DSMB. The charter is usually drafted
by the PO and subject to approval by PIs and DSMB members (see section
5.1 in Essential Documents that details the contents of the DSMB
Charter) (link). The DSMB Charter should be maintained in the Essential
Documents binder.

#### Create DSMB Report Templates and Meeting Documentation
The next step is for the research team to work with the DSMB members to
create templates for the Open and Closed Sessions of the DSMB meetings.
Templates for these reports are described in [section 5.2] of the
Essential Documents section \[add link\]. Finally, a system to maintain
agendas and minutes from the DSMB meetings should be established. All
DSMB reports, agendas and minutes must be maintained in the Essential
Documents binder.

#### Establish Meeting Schedule and Structure 
*Prior to the start of the trial*, the DSMB should convene as many times
as needed to review the protocol and approve all data safety monitoring
protocols, templates of essential documents, and processes for
conducting the business of the DSMB (e.g., schedule, voting rules,
minutes, definition of a quorum).

Unless otherwise determined, the PO is responsible for convening
meetings, and coordinating the distribution of materials to DSMB members
and other meeting participants prior to the meeting. The agenda for each
meeting is generally developed jointly by the PO, the PI (s) (regardless
of whether a contract, cooperative agreement, or grant), the study
statistician, and DSMB Chair. These details of these responsibilities
should be agreed upon by the PO and PI (s).

Once a study has started, most DSMBs meet every 6 months, but at least
annually. Additional DSMB meetings may be requested by DSMB members, the
PO, collaborators, IRB, or PI at any time and up to the discretion of
the PO and DSMB Chair.

Meetings may be held by telephone, videoconferences or in-person In the
event a DSMB member cannot attend a meeting, he/she may receive a copy
of the closed session DSMB report (see below) and either participate by
conference call or provide written comments to the DSMB Chair for
consideration at the meeting.

##### DSMB Meeting Format

The recommended meeting format consists of three sessions: Open Session,
Closed Session, and Closed Executive Session.

**A. Open Session *(****see
https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/data-and-safety-monitoring
for report template)*: This session is generally attended by the PI (s),
project statistician, external DSMB members, and the PO. The opens
session basically involves a complete review and discussion of all the
elements in the open session report presented in the aggregate for both
arms of the study.

**B. Closed Session *(****see
https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/data-and-safety-monitoring
for report template)*: Generally only external voting members attend
this meeting. However the DSMB may invite others to participate. The
data reviewed in the closed session is similar to that presented in the
open session, but is presented by study-arm in a semi-blinded fashion.
For example, the arms are NOT identified by control or intervention, but
as group 1 and group 2. If a study has an interim analysis with a
pre-determined stopping rule, outcomes with statistical comparisons are
also discussed in the closed session.

**C. Closed Executive Session**: This final session involves only DSMB
voting members to ensure complete objectivity as they discuss outcome
results, make decisions, and formulate recommendations regarding the
study. If treatment codes have been made accessible to the DSMB, then
the DSMB may unmask the data based on procedures identified in advance.

##### Voting

To hold a vote, a quorum, as defined by the DSMB in the initial meeting,
must be present either in person or by conference call. After a thorough
discussion, the final recommendations of each DSMB member should be
solicited in Closed Executive Session. A consensus recommendation among
members is not required. The final recommendations are identified as
majority or minority positions and are accompanied by actual vote
tallies for each divergent recommendation, i.e., as number of votes for
or against a particular action, such as continuing or terminating a
study, etc.

At the conclusion of the meeting, the DSMB sends their recommendations
to the PO and PI as to whether the study should continue without change,
be modified, or terminated. Recommendations could include:

-   Modifications of the study protocol

-   Suspension or early termination of the study or of one or more study
    arms because of serious concerns about subjects’ safety, inadequate
    performance or rate of enrollment

-   Suspension or early termination of the study or of one or more study
    arms because study objectives have been obtained according to
    pre-established statistical guidelines

-   Corrective actions regarding a study center whose performance
    appears unsatisfactory or suspicious.

Investigator must submit the DSMBs summary report to the IRB and any
other site investigators for distribution to other IRBs as necessary as
soon as it is available. DSMB/C reports should include a statement
indicating that the data have been reviewed, the date of review and a
summary of specific findings of the research study. If it is an
FDA-regulated trial the summary report must be forwarded to the FDA.

### Special considerations for older subjects 
NONE

### Common Pitfalls 
-   Failure to establish a DSMB
-   Not communicating DSMB activities to the IRB
-   Not reporting all required data/information in DSMB reports
-   Not preparing DSMB reports within an adequate time frame before the
    meeting
-   Failure to establish a collegial and open working collaboration
    between the research team and DSMB

### Resources 
-   Guidelines for data and safety monitoring for clinical trials not
    requiring traditional data monitoring committees,
    <http://www.sctweb.org/public/pubs/positionpapers/s6.pdf>
-   National Institute on Aging Clinical Research Study Investigator’s
    toolbox, Data Safety Monitoring,\*
    <https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/data-and-safety-monitoring>
-   National Institute of Dental and Craniofacial Research Toolkit for
    Clinical Researchers, DSMB guideline\*,
    <http://www.nidcr.nih.gov/Research/ToolsforResearchers/Toolkit/DSMBGuidelines.htm>

## Informed Consent
### What

Informed consent is the process by which a volunteer who wishes to
participate in a research study is informed about the study and agrees
to participate in the study. Informed consent is a process that
generally starts with the recruitment of volunteers and continues often
times throughout the course of a study.

Informed consent is a critical and complex regulatory component of human
subjects’ research, a full discussion of which goes beyond the scope of
this module. [Sections 45 CFR §46.116 and 45 CFR §46.117 of the Code of
Federal
Regulations](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)
Protection of Human Subjects
addresses informed consent. There are many other resources that provide
a thorough review of this topic, several of which, including the [HSL
IRB SOPs](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx)
are provided at the end of the module.

### Why
Informed consent is required under federal regulations for all
non-exempt research unless certain criteria are met to waive informed
consent requirements. The goal of the informed consent process is to
provide sufficient information so that participants can make informed
decisions about whether or not to enroll in a study or to continue or to
withdraw their participation.

### How
#### Who Obtains Consent?

The act of consenting participants may be completed by a trained member
of the research team, often a research nurse or assistant. However, the
PI bears responsibility for ensuring that informed consent is obtained
properly.

#### Who Gives Consent?

Consent is usually obtained from intended participants. However when the
intended participant lacks decision making capacity (e.g., too ill or
cognitively impaired) consent may be obtained from the intended
participant’s proxy or “legally authorized representative” (LAR) under
certain circumstances.

#### Mode of Consent

The mode of obtaining consent varies depending on the nature of the
study and study population. The gold standard is written consent,
however obtaining written informed consent is not always feasible or the
best choice for the research project. In these cases, with the guidance
and approval of the IRB, some or all aspects of informed consent may be
altered or waived. See also
[45](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)
[CFR 46.116 sections C and D, and 45 CFR 46.117 section
C](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)
of the Code of Federal Regulations Protection of Human Subjects.

##### Written Informed Consent Forms

A written consent form serves multiple purposes. It is a legal document
of consent, it can provide a helpful “script” during the process of
obtaining consent, and serves as a resource that participants can keep
and refer to throughout the study. Each institution’s IRB has specific
requirements and templates for written consent forms that must be
adhered to.

##### Waiver of consent 

There are very specific regulations that provide for circumstances under
which informed consent, or elements of informed consent, may be waived.
The determination of a waiver of consent is made by the overseeing IRB.
Also see [45 CFR 46.116 sections C and D, and 45 CFR 46.117 section
C](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html)
of the Code of Federal Regulations Protection of Human Subjects.

In the vast majority of cases, a waiver of consent is only possible for
clinical trials that meet the criteria for a “[minimal
risk](http://www.hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46/index.html#46.102)”
study
as defined in the Code of Federal Regulation, Protection of Human
subjects at ([45 CFR
§46.102(i)](http://www.hhs.gov/ohrp/humansubjects/guidance/45cfr46.html#46.102))
*“**Minimal risk means that
the probability and magnitude of harm or discomfort anticipated in the
research are not greater in and of themselves than those ordinarily
encountered in daily life or during the performance of routine physical
or psychological examinations or tests*.”

Whether or not a clinical trial meets criteria for a waiver of informed
consent has very important implications for the study design including
its timeline, budget, and personnel requirements. Thus, even in the
grant preparation stage you should consult with your IRB to get guidance
on this issue.

#### Special Situations and Settings

##### Informed consent in cluster RCTs 

In [cluster RCTs
](http://www.cochrane-net.org/openlearning/html/modA2-4.htm)the unit of
random assignment is a group (the “cluster”), such as a clinic,
hospital, physician practice or even a geographical region, rather than
an individual. This increasingly used design in health services research
raises many special ethical and regulatory considerations, including
informed consent. (See [The Ottawa Statement on Ethical Design and
Conduct of Cluster Randomized
Trials](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001346),
[When is Informed Consent Required in Cluster randomized trial in health
research?](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3184061/pdf/1745-6215-12-202.pdf)
and “[Ethical issues posed by cluster
RCTs](http://trialsjournal.biomedcentral.com/articles/10.1186/1745-6215-12-100),”

The following example illustrates some of these considerations

###### Considerations for informed consent within cluster trials:

-   *Identifying research participants*. Who meets the definition of a
    “human subject” from whom we should consider obtaining consent?

    -   Are providers subjects if they are implementing the intervention
        and data are being collected from them?

-   *Obtaining informed consent*.

<!-- -->

-   Can informed consent from individual patients be waived? Does the
    trial meet criteria for a minimal risk study?

-   If individual informed consent is required, when should it be
    obtained, before or after the facility is randomized?

### Special considerations for older subjects

Due to issues such as multiple and advanced illnesses, or impaired
capacity to consent to research, extra consideration needs to be made to
ensure that the rights and welfare of research participants who are
older are protected. For guidance on the issues see [NIH Research
Involving Individuals with Questionable Capacity to Consent; Points to
Consider](http://grants.nih.gov/grants/policy/questionablecapacity.htm). HSL
IRB specific guidelines are found in the SOPs

### Common Pitfalls
-   Not conferring early in trial planning stages with your IRB about
    informed consent requirements.

-   Inadequate storage of consent documents that protect confidentiality

-   Inadequate consent form: i.e., language not appropriate for target
    audience, font too small to read for older adults,
    contents incomplete.

### Resources 
External

-   ClinicalTrials, Informed consent,
    <http://www.clinicaltrials.com/investigators/informed_consent.htm>

-   FDA, Informed Consent Information Sheet, Guidance for IRBs, Clinical
    Investigators and sponsors,
    <http://www.fda.gov/RegulatoryInformation/Guidances/ucm404975.htm>

-   NIA NIH, Clinical Research Study Investigators Toolbox,
    <https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/informed-consent>

-   NIH Collaboratory, Rethinking Clinical Trials, Informed Consent,
    <http://sites.duke.edu/rethinkingclinicaltrials/informed-consent-in-pragmatic-clinical-trials/>

-   Ottawa Statement on the Ethical Design and Conduct of Cluster
    Randomized Trials,
    <http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001346>

-   Research Involving Individuals with Questionable Capacity to
    Consent: Points to consider,
    <http://grants.nih.gov/grants/policy/questionablecapacity.htm>

-   When is Informed Consent Required in Cluster randomized trial in
    health research?
    <http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3184061/pdf/1745-6215-12-202.pdf>

Internal

-   HSL IRB Policy and Procedures,
    <http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx>

## Adverse Events and Unanticipated Problems

There are numerous entities under which there is regulatory guidance on
classifying and reporting unanticipated problems and adverse events
(AEs), including the prime IRB, OHRP, NIH, HHS, and FDA. Investigators
must be apprised of the guidelines specific to their IRB and agencies
overseeing the trial.

### Pre-trial preparation for Adverse Event monitoring and reporting

Investigators must include a plan for defining, detecting, monitoring
and reporting any AEs that might occur in study subjects, including the
type, probability and expected level of severity. The investigator
should include a risk profile of the proposed research study as well as
a description of how the risks of the research will be minimized and the
plan for safety monitoring. Additionally, a description of potential AEs
must be included in the manual of operating procedures, all
regulatory/human subjects documents, DSMB, and consent forms.

### Reporting Processes around AEs and Unanticipated problems

All AEs experienced by study participants and all unanticipated problems
must be documented and reported as described in the study protocol.
Adverse Events (AEs), Serious Adverse Events (SAEs), and Unanticipated
Problems have specific definitions, reporting procedures and reporting
requirements that may vary by sponsor, internal IRB requirements and
study risk profile.

Detailed descriptions [NIAs requirements for reporting of the different
categories of adverse
events](https://www.nia.nih.gov/research/dgcg/clinical-research-study-investigators-toolbox/adverse-events)
can be found in the NIA Clinical Research Study Investigator’s Toolbox.
HSL’s IRB requirements are documented in the [HSL IRB
SOP](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx).

### Special considerations for older subjects 
NONE

### Common Pitfalls

-   Not understanding what needs to be communicated to the IRB, DSMB or
    other regulatory body overseeing the research.

-   Not communicating adverse events or unanticipated problems in the
    timeline required by regulatory bodies.

### Resources
External
-   FDA Guidance for Clinical Investigators, Sponsors, and IRBs, Adverse
    Event Reporting to IRBs – Improving Human Subject Protection,
    <http://www.fda.gov/downloads/RegulatoryInformation/Guidances/UCM126572.pdf>

-   HHS Guidance on Reviewing and Reporting Unanticipated Problems
    Involving Risks to Subjects or Others and Adverse Events,
    <http://www.hhs.gov/ohrp/policy/advevntguid.html>

-   NIH Definitions and Acronyms,
    <https://grants.nih.gov/ClinicalTrials_fdaaa/definitions.htm>

-   NIH Guidance on Reporting Adverse Events to Institutional Review
    Boards for NIH-Supported Multicenter Clinical Trials,
    <https://grants.nih.gov/grants/guide/notice-files/not99-107.html>

Internal

-   [HSL IRB
    SOP](http://thehslhub/~/media/HSLNet/Docs/IFAR/IRB/IRB_SOP.ashx)
