# Publication and Dissemination   

## Introduction
Research dissemination can be defined as follows: *“A planned process
that involves consideration of target audiences and the settings in
which research findings are to be received and, where appropriate,
communicating and interacting with wider policy and health service
audiences in ways that will facilitate research uptake in decision-
making processes and practice”* (Wilson *et al.* 2010, 5:91).

Traditionally, research dissemination centers on the publication of
results in peer reviewed journals and academic conference presentations.
Recent initiatives seek to broaden the concept of research dissemination
such that the main messages from results are communicated to targeted
decision-makers and stakeholders in a way that encourages them to factor
the research implications into their work and clinical practice. This
module will focus on two aspects of dissemination particularly relevant
to Clinical Trials: 1. Data sharing and 2. Publication in scientific
journals.

Regardless of the scope, researchers are encouraged to **develop a
dissemination plan early in the course of all trials.** Trials that are
closer to later phases of research translation (i.e., implementation)
and those supported by certain agencies (e.g., Patient-Centered Outcomes
Research Institute (PCORI)) may require more robust dissemination plans
in grant applications that go beyond traditional journal publications
and meeting presentations.

Resources for dissemination planning beyond journal publication:

-   Agency for Healthcare Research and Quality
    <http://www.ahrq.gov/professionals/quality-patient-safety/patient-safety-resources/resources/advances-in-patient-safety/vol4/planningtool.html>
-   Communications Handbook for Clinical Trials, Chapter 6, Preparing
    for and Disseminating Study Results,
    <http://www.fhi360.org/sites/default/files/media/documents/CommhandbkChapterSix.pdf>
-   Community Alliance for Research and Engagement, Beyond a Scientific
    Publication: Strategies for Disseminating Research Findings,”
    <https://ictr.wisc.edu/wp-content/uploads/2016/10/CAREStrategiesForDisseminating.pdf>
-   Wilson, P.M., M. Petticrew, M.W. Calnan, and I, Nazareth (2010) Disseminating research findings: What should researchers do? A
    systematic scoping review of conceptual frameworks. [*Implementation Science*, 5:91](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2994786/).

## Data Sharing
### What
To maximize transparency and investment, policymakers seek to expand
public and investigator access to clinical trial data. The extent of
data sharing can range from sharing aggregated data describing subject
characteristics and outcomes, to providing de-identified patient-level
data. Data sharing requirements depend on evolving policies of funding
agencies (i.e., NIH) and other regulators. **Researchers are strongly
encouraged to consult the most up-to-date requirements as early as
possible in planning of their clinical trial** (see How below).

### Why
The intent of data sharing is to maximize the transparency and benefits
of research. Moreover, some level of data sharing for clinical trials is
often required by regulatory authorities, funding agencies and the
ICMJE.

When done appropriately, data sharing:

-   Increases public trust by increasing transparency of research
    efforts
-   Maximizes the public health impact of research
-   Encourages scientific inquiry and new research efforts
-   Encourages diversity of analysis and opinion
-   Permits the creation of new datasets when data from multiple sources
    are combined

### How

In September 2016 the Department of Health and Human Services (HHS)
issued a new regulation and the NIH has issued a new policy to increase
the availability of information about clinical trials.  The HHS [Final Rule](https://www.federalregister.gov/documents/2016/09/21/2016-22129/clinical-trials-registration-and-results-information-submission)
describes requirements for registering and submitting summary results
information for certain clinical trials to [ClinicalTrials.gov](https://clinicaltrials.gov/). 
A complimentary [NIH policy](https://www.federalregister.gov/documents/2016/09/21/2016-22379/dissemination-of-nih-funded-clinical-trial-information)
that applies to all clinical trials funded by NIH, regardless of whether
they are subject to the Final Rule was also published on September 2016. The Final
NIH Policy was also published in the [NIH Guide for Grants and Contracts](http://grants.nih.gov/grants/guide/notice-files/NOT-OD-16-149.html).

NIH has made available the following resources to help explain these
changes. 

-   [A summary of the Final Rule and NIH policy](https://www.nih.gov/news-events/summary-hhs-nih-initiatives-enhance-availability-clinical-trial-information)
-   [Summary table of HHS/NIH initiatives to enhance availability of Clinical tial information](https://www.nih.gov/news-events/summary-table-hhs-nih-initiatives-enhance-availability-clinical-trial-information)
-   [A summary table of changes from current practice described in the Final Rule](https://prsinfo.clinicaltrials.gov/FinalRuleChanges-16Sept2016.pdf)

#### Methods for data sharing

There are numerous approaches to data sharing, each of which has
different levels of privacy protection and mechanisms for sharing.
Researchers can manage requests for data personally on an individual
request basis, or through use of a secure data archive or enclave.
Investigators should select a mode of data sharing that is appropriate
based on the size, complexity and sensitivity of the data, as well as
the volume of data use requests anticipated. See the [NIH data sharing guidance](<http://grants.nih.gov/grants/policy/data_sharing/data_sharing_guidance.htm#methods>)
for details.

The NIH provides numerous [data sharing repositories](https://www.nlm.nih.gov/NIHbmic/nih_data_sharing_repositories.html)
which make data accessible for reuse. If you are doing an NIH funded
trial, consult your Project Officer to discuss options for sharing data.

IFAR has created several sensitive data policies (including data access,
encryption, sharing, security, suppression, retention and destruction,
etc.) please see these policies on the [HSL HUB policy and forms](http://thehslhub/Departments/Roslindale/HSL-IFAR/Administration/Policies-and-Forms).

#### Human subjects and privacy issues

All data sharing activities must be compliant with HIPAA, local, state
and organizational regulations. All compliances and restrictions should
be addressed in the data sharing plan section of the funding
application. There are two basic approaches to protecting sensitive
data: restricting information in the shared dataset, and restricting
access to the data. See NIH [data sharing guidance](<https://grants.nih.gov/grants/policy/data_sharing/data_sharing_guidance.htm#methods)
for details.

**Restricting Information in the Dataset**

The plan for data sharing may include stripping a dataset of all
potential participant identifiers. Depending on the data and study
population, the level of information that will need to be removed from
the database varies. Studies involving participants with unusual
characteristics (Samples drawn from small geographic areas, rare
populations, and linked datasets) will likely involve a greater degree
of anonymizing to ensure the privacy of study participants.

**Restricting Access to the Dataset**

Data archives and enclaves can be set up to restrict access at any
level. Data Use Agreements restrict the use of data to those
specifically identified in the agreement, and require that data be used
only for research purposes.

Please see the [IFAR policy on Limited Data Sets and Data Use Agreements](http://thehslhub/Departments/Roslindale/HSL-IFAR/Administration/Policies-and-Forms)
on the HSL HUB as well as the [HSL IRB SOPs on HIPAA and the use of data in research](http://thehslhub/Forms/Documents-and-Forms/IFAR/IFAR-IRB-SOP).

## Special Considerations for Older Subjects 

NONE

## Common Pitfalls

-   Not being aware of and planning for up-to-date data sharing requirements by funding agencies, regulators, and ICMJE
-   Failure to develop a clear well documented dataset can undermine the researchers ability to share the data or others to use it.
-   Failure to plan for the time and expense of data sharing

### Resources 

External

-   [A summary of the Final Rule and NIH policy](https://www.nih.gov/news-events/summary-hhs-nih-initiatives-enhance-availability-clinical-trial-information)
-   A table of the key elements of the Final Rule and NIH policy, (https://www.nih.gov/news-events/summary-table-hhs-nih-initiatives-enhance-availability-clinical-trial-information)
-   A summary table of changes from current practice described in the Final Rule, (https://prsinfo.clinicaltrials.gov/FinalRuleChanges-16Sept2016.pdf)
-   Clinicaltrials.gov, (https://clinicaltrials.gov/)
-   NIH Policy on the dissemination of NIH funded clinical trial information, (http://grants.nih.gov/grants/guide/notice-files/NOT-OD-16-149.html).

Internal

-   HSL IFAR Data Policies, (http://thehslhub/Departments/Roslindale/HSL-IFAR/Administration/Policies-and-Forms)
-   HSL IRB Policies and Procedures, (http://thehslhub/Forms/Documents-and-Forms/IFAR/IFAR-IRB-SOP)

## Scientific Publications and Presentations

### General considerations

All paper and abstracts emanating from your trial should be planned
early on in the study to maximize the productivity from the trial and
avoid iterative papers. In planning, it is useful to outline the topic
of paper, target journal and responsible first author.

Larger trials should have a *Publications Steering Committee* whose
members are usually the lead investigators and establish written
guidelines for vetting papers emanating from the trial. This procedure
for planning, reviewing and approving all scientific publications
(papers and abstracts) prior to submission is to ensure they are accurate
(i.e., align with protocol), not duplicative, and respect ICMJE
authorship guidelines. Certain funding agencies and industry trial sponsors
may have very specific requirements regarding their own review
and approval of manuscripts prior to submission.

Section III of the [ACRIN publication policy](https://www.acrin.org/RESEARCHERS/POLICIES/PUBLICATIONSPOLICY/PUBLICATIONSPOLICYDOCUMENT.aspx)
provides details related to the roles and responsibilities of
publication committees.

### Specific reporting guidelines for clinical trials

There are specific reporting guidelines for clinical trials that differ
by the trial type which are continually being updated. For
example, there are set standards for the flow diagrams presenting
subject participation in a clinical trial that differ between
traditional parallel design randomized trials, non-inferiority trials,
cluster randomized trials, stepped wedge designs etc. Journals generally
follow the guidelines described in the Consolidated
Standards of Reporting Trials ([**CONSORT**](http://www.consort-statement.org/)) statement].

The Enhancing the QUAlity and Transparency Of health Research network [(EQUATOR](http://www.equator-network.org/)
is a very useful comprehensible searchable website with up-to-date
links to the CONSORT statements and extensions.

### Publication of the trial protocol 
#### What
Protocol manuscripts report the methodology of your clinical trial.
Details in a published protocol paper (e.g., primary and secondary
outcome definitions, sample size estimates) need to align with other
official communications describing the study’s methodology such as the
trial protocol and descriptions in ClinicalTrials.gov. These documents
may be compared by journals considering publication of the trial’s
results and discrepancies will need to be explained.

#### Why
Reasons to publish a protocol paper include increasing transparency of
the trial conduct, providing a detailed reference for future
publications emanating from the study, and demonstrating productivity
for funding agencies.

#### How
Planning for a protocol manuscript submission should begin early because
journals generally only consider publishing protocol papers for studies
that have received ethics approval but have not yet concluded patient
recruitment.

##### Selecting a journal
Examples of journals that publish protocol papers include: Clinical
Trials: Journal of the Society of Clinical Trials, Contemporary Clinical
Trials, International Journal of Clinical Trials, Journal of Clinical
Trials, BMJ, and Trials. Some of these journals allow authors to pay for
publication of their protocol paper (e.g., Journal of Clinical Trials)
and others have the option of paying for open access should the paper be
accepted.

In deciding which journal is the most appropriate to publish your
protocol, it is useful to first review prior protocol papers published
in specific journals to see which best aligns with your study and
examine their formats. All journals will have specific guidelines for
preparation which should be carefully consulted and adhered to.

### Publication of the results of a clinical trial
#### Timing
The [WHO](http://www.who.int/ictrp/results/reporting/en/) 
statement on Public Disclosure of Clinical Trial Results states, 
at a minimum,main findings of clinical trials, positive or negative, are to be
submitted for publication in a peer reviewed journal within 12 months of
study completion and are to be published through an open access
mechanism unless there is a specific reason why open access cannot be
used, or otherwise made available publicly at most within 24 months of
study completion.

#### Trial registration identification
As per the [ICMJE guidelines](http://www.icmje.org/recommendations/browse/manuscript-preparation/preparing-for-submission.html),
top-tier journals require that your trial be registered on [ClinicalTrials.gov](https://clinicaltrials.gov/)
(or equivalent such as WHO International Clinical Trials Registry Platform 
[(ICTRP)](http://www.who.int/ictrp/network/primary/en/index.html)) prior
to the enrollment of the first subject, otherwise the paper will be
rejected without review. The trial registration number must be included
in your manuscript and usually appears at the end of the abstract.

The ICMJE encourages posting of clinical trial results in clinical trial
registries. The ICMJE will not consider as prior publication the posting
of trial results in any registry that meets the above criteria if
results are limited to a brief (500 word) structured abstract or tables
(to include patients enrolled, key outcomes, and adverse events).

#### Packaging results
Investigators are cautioned to carefully plan the paper (s) emanating
from a single trial to avoid iterative publications, ensure the main
trial results are not usurped by early papers, and to adhere with the
pre-specified analyses set forth in the trial protocol and as described
on ClinicalTrials.gov. One should reserve the main paper to include the
pre-specified primary and secondary outcomes. *“Outcome switching”
(i.e., changing the outcomes reported in results paper with those
pre-specified in the protocol and on ClinicalTrials.gov) must be
avoided.*

Following publication of the main paper, non-iterative auxiliary papers
that leverage the rich clinical trials data may be considered.

#### Manuscript preparation
All manuscripts should adhere to the guidelines provided in each
journals’ Instructions for Authors which generally follow [ICMJE guidelines](http://www.icmje.org/recommendations/browse/manuscript-preparation/preparing-for-submission.html).

Most journals which have a specific reporting criteria for clinical
trials results manuscripts which generally follow the [CONSORT
statement](http://www.consort-statement.org/). CONSORT provides an extremely
useful [checklist](http://www.consort-statement.org/checklists/view/32-consort/66-title)
to help guide presentation of every element of a clinical trial
manuscript and is a **highly recommended resource.**

#### Adjunct material
Most top tier journals will request a copy of the trial protocol with
the submission of the paper describing the clinical trial results.
Editors will compare the details in the protocol, ClinicalTrials.gov and
any previously published protocol papers, with those described in the
submitted manuscript to ensure they align.

### Special considerations for older subjects 
NONE

### Common pitfalls
-   Failure to develop a publication plan and committee early in the
    course of the trial.
-   Failure to register the trial on ClinicalTrials.gov prior to
    enrollment of the first subject.
-   Failure to submit trial results for publication within 12 months of
    trial completion and failure to publish results within 24 months.
-   Failure to follow ICMJE, journal specific, and CONSORT guidelines
    for preparing clinical trials publications.
-   Failure to align details of the trial in submitted papers to details
    as described in the protocol and on ClinicalTrials.gov, particularly
    pre-specified primary and secondary outcomes
-   Publishing iterative papers or early papers that usurp publication
    of main findings.
-   Missing opportunities for results dissemination beyond peer reviewed
    journals and professional conferences.

### Resources 

-   American College of Radiology Imaging Network Publications Policy,
    <https://www.acrin.org/RESEARCHERS/POLICIES/PUBLICATIONSPOLICY/PUBLICATIONSPOLICYDOCUMENT.aspx>
-   Author’s Submission Toolkit: A Practical Guide to getting your
    research Published, Current Medical Research & Opinion Vol 26, No 8,
    2010 1967-1982.
    <http://www.ismpp.org/assets/docs/Certification/StudyMaterials/patel%20m%202010.pdf>
-   CONSORT (Consolidated Standards of Reporting Trials) statement
    <http://www.consort-statement.org/>
-   Equator Network Essential resources for writing and publishing
    health research, <http://www.equator-network.org/>
-   General ICMJE guidelines for preparing manuscripts for publication
    in scientific journals
    <http://www.icmje.org/recommendations/browse/manuscript-preparation/preparing-for-submission.html>
-   WHO statement on timing of clinical trials results
    <http://www.who.int/ictrp/results/reporting/en/>
