# Site settings
title: ISAC - Interventional Studies in Aging Center
email: TGT@hsl.harvard.edu
description: The IFAR Biostatistics Core is dedicated to provide high quality data management and analysis services in clinical research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  IFARbiostats

# Build settings
markdown: kramdown
# markdown: redcarpet
# redcarpet:
#   extensions: [with_toc_data]
